- name: PLAY-1
  hosts: localhost #where ansible is running or you can say where you run the playbook 
  tasks:
    - name: PLAY-1 and TASK-1
    ansible.builtin.debug:
      msg: "Hello I am from PLAY-1 and TASK-1"

- name: PLAY-2
  hosts: localhost
  tasks:
    - name: PLAY-2 and TASK-1
    ansible.builtin.debug: # debug is like echo it will print message
      msg: "Hello I am from PLAY-2 and TASK-1"


# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password= multi-play.yaml